# Logistic Regression

### Importing Libraries

In [1]:
#importing libraries 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

### Importing the data

In [2]:
data = pd.read_csv('data_cleaned.csv')
data.head()

Survived   Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0         0  22.0   7.2500         0         0         1           0   
1         1  38.0  71.2833         1         0         0           1   
2         1  26.0   7.9250         0         0         1           1   
3         1  35.0  53.1000         1         0         0           1   
4         0  35.0   8.0500         0         0         1           0   

   Sex_male  SibSp_0  SibSp_1  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0         1        0        1  ...        1        0        0        0   
1         0        0        1  ...        1        0        0        0   
2         0        1        0  ...        1        0        0        0   
3         0        0        1  ...        1        0        0        0   
4         1        1        0  ...        1        0        0        0   

   Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0        0        0        0           0           0           1  
1        0        0        0           1           0           0  
2        0        0        0           0           0           1  
3        0        0        0           0           0           1  
4        0        0        0           0           0           1  

[5 rows x 25 columns]

### Segregating variables: Independent and Dependent Variables

In [3]:
#seperating independent and dependent variables
x = data.drop(['Survived'], axis=1)
y = data['Survived']
x.shape, y.shape

((891, 24), (891,))

In [8]:
#x is of dataframe type

### Splitting the data into train set and the test set

In [12]:
# Importing the train test split function
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(x,y, random_state = 56)

In [49]:
train_y.dtype

dtype('int64')

### Normalising using *min_max_scaler*

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [14]:
cols = train_x.columns
cols

Index(['Age', 'Fare', 'Pclass_1', 'Pclass_2', 'Pclass_3', 'Sex_female',
       'Sex_male', 'SibSp_0', 'SibSp_1', 'SibSp_2', 'SibSp_3', 'SibSp_4',
       'SibSp_5', 'SibSp_8', 'Parch_0', 'Parch_1', 'Parch_2', 'Parch_3',
       'Parch_4', 'Parch_5', 'Parch_6', 'Embarked_C', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')

In [19]:
#train_x_scaled = scaler.fit_transform(train_x)
#train_x_scaled.type
#numpy array return by fit transform function

In [20]:
train_x_scaled = scaler.fit_transform(train_x)
train_x_scaled = pd.DataFrame(train_x_scaled, columns=cols)
train_x_scaled.head()

Age      Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  Sex_male  \
0  0.371701  0.024350       0.0       0.0       1.0         1.0       0.0   
1  0.334004  0.016908       0.0       0.0       1.0         0.0       1.0   
2  0.396833  0.015127       0.0       0.0       1.0         0.0       1.0   
3  0.786378  0.152164       1.0       0.0       0.0         1.0       0.0   
4  0.334004  0.412821       1.0       0.0       0.0         0.0       1.0   

   SibSp_0  SibSp_1  SibSp_2  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0      1.0      0.0      0.0  ...      1.0      0.0      0.0      0.0   
1      1.0      0.0      0.0  ...      1.0      0.0      0.0      0.0   
2      1.0      0.0      0.0  ...      1.0      0.0      0.0      0.0   
3      0.0      1.0      0.0  ...      1.0      0.0      0.0      0.0   
4      1.0      0.0      0.0  ...      0.0      0.0      1.0      0.0   

   Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0      0.0      0.0      0.0         0.0         0.0         1.0  
1      0.0      0.0      0.0         0.0         0.0         1.0  
2      0.0      0.0      0.0         0.0         1.0         0.0  
3      0.0      0.0      0.0         0.0         0.0         1.0  
4      0.0      0.0      0.0         1.0         0.0         0.0  

[5 rows x 24 columns]

In [21]:
test_x_scaled = scaler.transform(test_x)
test_x_scaled = pd.DataFrame(test_x_scaled, columns=cols)
test_x_scaled.head()

Age      Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  Sex_male  \
0  0.396833  0.143462       0.0       1.0       0.0         0.0       1.0   
1  0.359135  0.129995       1.0       0.0       0.0         0.0       1.0   
2  0.367921  0.014110       0.0       0.0       1.0         0.0       1.0   
3  0.346569  0.025374       0.0       1.0       0.0         1.0       0.0   
4  0.371701  0.054164       1.0       0.0       0.0         0.0       1.0   

   SibSp_0  SibSp_1  SibSp_2  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0      0.0      0.0      1.0  ...      1.0      0.0      0.0      0.0   
1      0.0      1.0      0.0  ...      1.0      0.0      0.0      0.0   
2      1.0      0.0      0.0  ...      1.0      0.0      0.0      0.0   
3      1.0      0.0      0.0  ...      1.0      0.0      0.0      0.0   
4      1.0      0.0      0.0  ...      1.0      0.0      0.0      0.0   

   Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0      0.0      0.0      0.0         0.0         0.0         1.0  
1      0.0      0.0      0.0         0.0         0.0         1.0  
2      0.0      0.0      0.0         1.0         0.0         0.0  
3      0.0      0.0      0.0         0.0         0.0         1.0  
4      0.0      0.0      0.0         1.0         0.0         0.0  

[5 rows x 24 columns]

### Implementing Logistic Regression

In [22]:
#importing Logistic Regression and metric F1-score
from sklearn.linear_model import LogisticRegression as LogReg
from sklearn.metrics import f1_score

In [23]:
# Creating instance of Logistic Regresssion
logreg = LogReg()

# Fitting the model
logreg.fit(train_x, train_y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

### Making predictions using *predict* function

In [24]:
# Predicting over the Train
train_predict = logreg.predict(train_x)
train_predict

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,

In [25]:
# Calculating f1-score
k = f1_score(train_predict, train_y)
print('Training f1_score', k )

Training f1_score 0.7485148514851485


In [26]:
# Predicting over the Test Set and f1-score
test_predict = logreg.predict(test_x)
k = f1_score(test_predict, test_y)
print('Test f1_score    ', k )

Test f1_score     0.7500000000000001


### Making predictions using *predict_proba* function

In [27]:
# Predicting over the Train
train_predict = logreg.predict_proba(train_x)
train_predict

array([[0.50532299, 0.49467701],
       [0.90358557, 0.09641443],
       [0.87905516, 0.12094484],
       ...,
       [0.23180909, 0.76819091],
       [0.3139615 , 0.6860385 ],
       [0.04488938, 0.95511062]])

In [33]:
a=np.array([[1,2],[3,4]])

In [34]:
a

array([[1, 2],
       [3, 4]])

In [38]:
a[1:,1]

array([4])

In [39]:
train_preds = train_predict[:,1]
train_preds

array([0.49467701, 0.09641443, 0.12094484, 0.7826964 , 0.63158769,
       0.11959969, 0.8276528 , 0.76837161, 0.52316437, 0.08819518,
       0.10903798, 0.08834939, 0.12710635, 0.09929297, 0.60742357,
       0.08735943, 0.30854485, 0.12325234, 0.07441008, 0.28061949,
       0.10585236, 0.21134167, 0.07037308, 0.59759534, 0.09323402,
       0.52618717, 0.08819866, 0.55834191, 0.59353586, 0.13131489,
       0.81433108, 0.08838542, 0.58424828, 0.12972118, 0.01941743,
       0.59135583, 0.21086397, 0.13152669, 0.0612354 , 0.27460293,
       0.84284741, 0.39026631, 0.20569125, 0.71795573, 0.48472526,
       0.94248256, 0.3573382 , 0.23520256, 0.17378959, 0.89340088,
       0.13552784, 0.63959863, 0.2301236 , 0.60033807, 0.34034369,
       0.64464108, 0.77324435, 0.28159577, 0.11224541, 0.30456324,
       0.59461467, 0.28159577, 0.13033412, 0.45512495, 0.10073301,
       0.97659383, 0.12001893, 0.08834939, 0.85824021, 0.67783387,
       0.93271438, 0.75637983, 0.89304459, 0.44658065, 0.83485

In [42]:
for i in range(0, len(train_preds)):
  if(train_preds[i]>0.55):
    train_preds[i] = 1
  else:
    train_preds[i] = 0
  

In [43]:
#train_preds.type numpy array

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [45]:
train_y.dtype

dtype('int64')

In [50]:
# Calculating f1-score
k = f1_score(train_preds, train_y)
print('Training f1_score', k )

Training f1_score 0.7428571428571429


# Confusion matrix

In [51]:
from sklearn.metrics import confusion_matrix
cf= confusion_matrix(test_y, test_predict)
print(cf)

[[128  16]
 [ 22  57]]


In [52]:
from sklearn.metrics import classification_report as rep
print(rep( test_y , test_predict ))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87       144
           1       0.78      0.72      0.75        79

    accuracy                           0.83       223
   macro avg       0.82      0.81      0.81       223
weighted avg       0.83      0.83      0.83       223



# Parameters of Logistic Regression

In [53]:
# printing the coefficients
logreg.coef_

array([[-0.03483324,  0.00290013,  0.9995272 ,  0.09486364, -1.05437925,
         1.17493838, -1.13492679,  0.876068  ,  1.08449093,  0.48118273,
        -0.58818058, -0.80578062, -0.43078884, -0.57698001,  0.23067554,
         0.6899365 , -0.08309987,  0.31876764, -0.59641794, -0.19446174,
        -0.32538854,  0.16857483,  0.15122559, -0.27978883]])

In [54]:
logreg.coef_.shape

(1, 24)

In [56]:
c = logreg.coef_.reshape(-1)
c

array([-0.03483324,  0.00290013,  0.9995272 ,  0.09486364, -1.05437925,
        1.17493838, -1.13492679,  0.876068  ,  1.08449093,  0.48118273,
       -0.58818058, -0.80578062, -0.43078884, -0.57698001,  0.23067554,
        0.6899365 , -0.08309987,  0.31876764, -0.59641794, -0.19446174,
       -0.32538854,  0.16857483,  0.15122559, -0.27978883])

### Plotting the coefficients

In [ ]:
plt.figure(figsize=(8, 6), dpi=120, facecolor='w', edgecolor='b')
x = range(len(train_x.columns))
c = logreg.coef_.reshape(-1)
plt.bar( x, c )
plt.xlabel( "Variables")
plt.ylabel('Coefficients')
plt.title('Coefficient plot')

In [ ]:
Coefficients = pd.DataFrame({
    'Variable'    : train_x.columns,
    'coefficient' : abs(c)
})
Coefficients.head()

In [ ]:
#selecting variables with high coefficient
sig_var = Coefficients[Coefficients.coefficient > 0.3)

In [ ]:
subset = data[sig_var['Variable'].values]
subset.head()

In [ ]:
# Using train test split function
train_x,test_x,train_y,test_y = train_test_split(subset, y, random_state = 56)

### Implementing Logistic Regression

In [ ]:
# Creating instance of Logistic Regresssion
logreg = LogReg()

# Fitting the model
logreg.fit(train_x, train_y)

### Making predictions using *predict* function

In [ ]:
# Predicting over the Train
train_predict = logreg.predict(train_x)
k = f1_score(train_predict, train_y)
print('Training f1_score', k )

In [ ]:
plt.figure(figsize=(8, 6), dpi=120, facecolor='w', edgecolor='b')
x = range(len(train_x.columns))
c = logreg.coef_.reshape(-1)
plt.bar( x, c )
plt.xlabel( "Variables")
plt.ylabel('Coefficients')
plt.title('Coefficient plot')